const express = require('express');
const connectDB = require('./db');
const employeeRoutes = require('./routes/employee');
const webhookRoutes = require('./routes/webhook');
const requestLogger = require('./middlewares/requestLogger');
const notFound = require('./middlewares/notFound');
const errorHandler = require('./middlewares/errorHandler');
const app = express();
const PORT = process.env.PORT || 5000;
app.use(express.json());
app.use(express.static('public'));
app.use(requestLogger);
connectDB();
app.use('/employees', employeeRoutes);
app.use('/webhooks', webhookRoutes);
app.use(notFound);
app.use(errorHandler);
app.listen(PORT, () => {
  console.log(`Server running on http://localhost:${PORT}`);
});
