const express = require('express');
const router = express.Router();
const { getAllEmployees, createEmployee, updateEmployee, deleteEmployee } = require('../controllers/employeeController');
const validate = require('../middlewares/validate');
const { validateCreate, validateUpdate } = require('../validators/employeeValidator');
router.get('/', getAllEmployees);
router.post('/', validate(validateCreate), createEmployee);
router.put('/:id', validate(validateUpdate), updateEmployee);
router.delete('/:id', deleteEmployee);
module.exports = router;
